### ISSUE TITLE
Missing item kind when using cmd_history

### ISSUE THREAD

**Issue by JoseConseco** [dmitmel/cmp-cmdline-history#1]
Here is cmd line suggestions without  cmd_history plugin:
![image](https://user-images.githubusercontent.com/13521338/141100362-af0bd78e-2e46-41df-bb51-c98cc20a8e35.png)
And with cmd_history 
![image](https://user-images.githubusercontent.com/13521338/141100542-6c6bd3e9-6a8f-4020-a451-6d171326d375.png)

Not sure why the item kind element is missing.  Maybe there was api change in cmp...

**Comment by dmitmel** [comment]
The menu with cmdline-history is so wide that the kind is off-screen

**Comment by dmitmel** [comment]
I guess I could truncate the completion results, but I would rather have a setting for this in nvim-cmp than this source

**Comment by JoseConseco** [comment]
well ok, but cmd-history make all items kind disappear.  cmp.setup has this function:
![image](https://user-images.githubusercontent.com/13521338/141102496-0ec9f9ee-e8dd-4b6e-a12f-8f08049e7277.png)

so you whould be able to override/define item  for new sources inside plugin right? Will see I I can find the solution

**Comment by dmitmel** [comment]
You probably misunderstood me. Try putting
```lua
vim_item.abbr = vim.fn.strcharpart(vim_item.abbr, 0, 50)
```
in your `format` function, you'll see that kind is actually there.

**Comment by JoseConseco** [comment]
EDITED: 
Ok , I have items  type displayed now for command line elements.  but can you shorten item abbr directly in your plugin? 
As seen in  first post -  element type is messed up with cmp-cmdline-history also for other sources.  The labels are back - when I disable cmdline-history

**Comment by JoseConseco** [comment]
ok I get it now -  it is the item content that need to be shortened- the label/abbr itself is ok. Damm I think slowly today. My bad closing.
